name: fcs_iac
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run FCS IaC Scan
        uses: crowdstrike/fcs-action@v1.0.5
        with:
          falcon_client_id: '${{ secrets.FALCON_CLIENT_ID }}'
          falcon_region: '${{ var.FALCON_CLOUD_REGION }}'
          path: './terraform/azure'
          upload_results: false
        env:
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
